version: '2'
services:
  hlgd:
    image: $HLGD_IMAGE
    build:
      context: .
      dockerfile: ./Dockerfile
    # entrypoint: [python, manage.py]
    # command: [runserver, '--host', '0.0.0.0', '--port', '80']
    entrypoint: [sh]
    volumes:
      - .:/src
      - ./container-logs:/var/log/eebook
    tty: true
    ports:
      - "$HLGD_API_PORT:80"
    env_file:
      - envs/local.env
      - envs/secret.env
    environment:
      - ENV="development"
      - no_proxy=true
    networks:
      - hlgd
  db:
    image: $POSTGRES_IMAGE
    ports:
      - "5432"
    env_file:
      - envs/local.env
    networks:
      - hlgd
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - '6379'
    volumes:
      - ./redis-data:/data
    networks:
      - hlgd

networks:
  hlgd:
    driver: bridge
