"""empty message

Revision ID: 3b834f0f3c0c
Revises: 
Create Date: 2017-11-17 07:15:30.466403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b834f0f3c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
