"""empty message

Revision ID: 9de9eed8fdfc
Revises: b2e825648b96
Create Date: 2017-12-12 02:32:49.629691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de9eed8fdfc'
down_revision = 'b2e825648b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('author', sa.String(length=128), nullable=True))
    op.add_column('metadata', sa.Column('author_link', sa.String(length=255), nullable=True))
    op.add_column('metadata', sa.Column('repo_type', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'repo_type')
    op.drop_column('metadata', 'author_link')
    op.drop_column('metadata', 'author')
    # ### end Alembic commands ###
