"""empty message

Revision ID: b2e825648b96
Revises: 24a6f104d789
Create Date: 2017-11-24 09:13:18.056494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e825648b96'
down_revision = '24a6f104d789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('metadata', sa.Column('image_version', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'image_version')
    op.drop_column('metadata', 'image')
    # ### end Alembic commands ###
