"""empty message

Revision ID: bc07f30303bf
Revises: 9de9eed8fdfc
Create Date: 2018-07-27 02:22:45.317346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc07f30303bf'
down_revision = '9de9eed8fdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'examples')
    # ### end Alembic commands ###
